services:
  admin:
    build:
      context: admin
    ports:
      - "8000:8000"
    volumes:
      - ./admin:/admin
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      
  fastapi:
    build:
      context: fastapi
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi:/fastapi
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8001"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine

    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass